# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
$ADD_HOST_INFO = <<SCRIPT
IP_ADDRESS=$(ip a s enp0s8 | grep '/24' | cut -d / -f1 | awk '{print $2}')
echo $IP_ADDRESS $HOSTNAME ${HOSTNAME%%.*} >> /etc/hosts
SCRIPT

PE_SOA_HOST_NAME = "soa-puppet01.harris-hc-lab.com"
PE_HOST_NAME = "pe.asde.com"
PE_PRIVATE_IP = "192.168.56.10"
NODE1_HOST_NAME = "node1.asde.com"
NODE1_PRIVATE_IP = "192.168.56.11"
NODE2_HOST_NAME = "node2.asde.com"
NODE2_PRIVATE_IP = "192.168.56.12"
NODE3_HOST_NAME = "node3.asde.com"
NODE3_PRIVATE_IP = "192.168.56.13"
NODE4_HOST_NAME = "node4.asde.com"
NODE4_PRIVATE_IP = "192.168.56.14"

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

#  config.vm.box = 'chef/centos-6.6'
#  config.vm.box_url = 'https://atlas.hashicorp.com/chef/boxes/centos-6.6'
  config.vm.box = 'sixpac009/centos71-base'
  config.ssh.forward_agent = true
    
  #config.vm.synced_folder "bootbox-shared", "/vagrant"
  #config.vm.synced_folder "../../",         "/genesis"
  #config.vm.synced_folder "files",            "/files"
  #config.vm.synced_folder "../git/soasuite/Puppet_Modules", "/modules_in_work"
  
  #config.vm.provision :shell, inline: $ADD_HOST_INFO
  config.vm.provision :shell, inline: "echo $1 $3 $2 ${2%%.*} >> /etc/hosts", args: [PE_PRIVATE_IP, PE_HOST_NAME, PE_SOA_HOST_NAME]
  config.vm.provision :shell, inline: "echo $1 $2 ${2%%.*} >> /etc/hosts", args: [NODE1_PRIVATE_IP, NODE1_HOST_NAME]
  config.vm.provision :shell, inline: "echo $1 $2 ${2%%.*} >> /etc/hosts", args: [NODE2_PRIVATE_IP, NODE2_HOST_NAME]
  config.vm.provision :shell, inline: "echo $1 $2 ${2%%.*} >> /etc/hosts", args: [NODE3_PRIVATE_IP, NODE3_HOST_NAME]
  config.vm.provision :shell, inline: "echo $1 $2 ${2%%.*} >> /etc/hosts", args: [NODE4_PRIVATE_IP, NODE4_HOST_NAME]
  config.vm.provision :shell, inline: "curl -k https://pe.asde.com:8140/packages/current/install.bash | sudo bash"
  config.vm.provision :shell, inline: "mkdir /apps"
  #config.puppet_install.puppet_version = :latest
  #config.puppet_install.puppet_version = '3.7.2'

  config.vm.define "node1" do |node1|
    node1.vm.hostname = NODE1_HOST_NAME
    node1.vm.network "private_network", ip: NODE1_PRIVATE_IP

    node1.vm.provider "virtualbox" do |v|
      v.name = "Test-Node1"
      v.gui = true
      v.cpus = 2
      # minimum should be considered to be 2048, but feel free to use any
      # value between 2048 and half your available system memory
      v.memory = 1048
    end
  end
  config.vm.define "node2" do |node2|
    node2.vm.hostname = NODE2_HOST_NAME
    node2.vm.network "private_network", ip: NODE2_PRIVATE_IP

    node2.vm.provider "virtualbox" do |v|
      v.name = "Test-Node2"
      v.gui = true
      v.cpus = 2
      # minimum should be considered to be 2048, but feel free to use any
      # value between 2048 and half your available system memory
      v.memory = 1048
    end
  end
  config.vm.define "node3" do |node3|
    node3.vm.hostname = NODE3_HOST_NAME
    node3.vm.network "private_network", ip: NODE3_PRIVATE_IP

    node3.vm.provider "virtualbox" do |v|
      v.name = "Test-Node3"
      v.gui = true
      v.cpus = 2
      # minimum should be considered to be 2048, but feel free to use any
      # value between 2048 and half your available system memory
      v.memory = 1048
    end
  end
  config.vm.define "node4" do |node4|
    node4.vm.hostname = NODE4_HOST_NAME
    node4.vm.network "private_network", ip: NODE4_PRIVATE_IP

    node4.vm.provider "virtualbox" do |v|
      v.name = "Test-Node4"
      v.gui = true
      v.cpus = 2
      # minimum should be considered to be 2048, but feel free to use any
      # value between 2048 and half your available system memory
      v.memory = 1048
    end
  end

end
